# Generated by Django 6.0.5 on 2026-05-29 03:19

from django.db import migrations, models


def rename_blocked_to_inactive(apps, schema_editor):
    User = apps.get_model('user', 'User')
    User.objects.filter(status='blocked').update(status='inactive')


def rename_inactive_to_blocked(apps, schema_editor):
    User = apps.get_model('user', 'User')
    User.objects.filter(status='inactive').update(status='blocked')


def sync_django_flags_from_role_status(apps, schema_editor):
    User = apps.get_model('user', 'User')
    for user in User.objects.iterator():
        is_staff = user.role in ('admin', 'staff')
        is_superuser = user.role == 'admin'
        is_active = user.status == 'active'
        User.objects.filter(pk=user.pk).update(
            is_staff=is_staff,
            is_superuser=is_superuser,
            is_active=is_active,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useraddress'),
    ]

    operations = [
        migrations.RunPython(
            rename_blocked_to_inactive,
            rename_inactive_to_blocked,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Admin'),
                    ('staff', 'Staff'),
                    ('seller', 'Seller'),
                    ('customer', 'Customer'),
                ],
                default='customer',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(
                choices=[('active', 'Active'), ('inactive', 'Inactive')],
                default='active',
                max_length=20,
            ),
        ),
        migrations.RunPython(
            sync_django_flags_from_role_status,
            migrations.RunPython.noop,
        ),
    ]
