# Generated by Django 6.0.5 on 2026-05-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_brand_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='created',
            new_name='created_at',
        ),
    ]
