# Generated by Django 6.0.5 on 2026-05-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("sold_out", "Sold out"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
