# Generated by Django 6.0.5 on 2026-05-28 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("product", "0003_productvariant_status"),
        ("user", "0002_useraddress"),
        ("voucher", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="unique_order_product_variant",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="order_order_sku_bda0a5_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_user_id_4e08b8_idx",
            old_name="order_order_user_id_a7f1ea_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_status_762191_idx",
            old_name="order_order_status_2f1723_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_created_77e2b9_idx",
            old_name="order_order_created_ffede0_idx",
        ),
        migrations.RenameIndex(
            model_name="orderitem",
            new_name="order_items_order_i_26ad88_idx",
            old_name="order_order_order_i_854de1_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="address_line",
        ),
        migrations.RemoveField(
            model_name="order",
            name="district",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="province",
        ),
        migrations.RemoveField(
            model_name="order",
            name="recipient_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_fee",
        ),
        migrations.RemoveField(
            model_name="order",
            name="subtotal_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="voucher_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="ward",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="user.useraddress",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="final_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="subtotal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="product.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["address"], name="orders_address_51df79_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["voucher"], name="orders_voucher_b52a43_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["product"], name="order_items_product_a53db1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["variant"], name="order_items_variant_27ce3c_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="order",
            table="orders",
        ),
        migrations.AlterModelTable(
            name="orderitem",
            table="order_items",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="line_total",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product_variant",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="variant_name",
        ),
    ]
